spec-version: 0.30.0
name: static-ls
author: Joseph Sumabat
maintainer: josephrsumabat@gmail.com
license: MIT

build-type: Simple

dependencies:
  - array
  - base
  - containers
  - directory
  - extra
  - filepath
  - ghc
  - ghc-paths
  - ghcide
  - hiedb
  - lsp
  - lsp-types
  - mtl
  - silently
  - template-haskell
  - text
  - transformers
  - unliftio-core

ghc-options:
  - -fwrite-ide-info
  - -hiedir .hiefiles
default-extensions:
- OverloadedRecordDot
- OverloadedStrings
- NoFieldSelectors
- LambdaCase

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - static-ls

tests:
  static-ls-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - static-ls
    - hspec
    - hspec-discover
    defaults: hspec/hspec@main
