spec-version: 0.30.0
name: static-ls
author: Joseph Sumabat
synopsis: See README on Github for more information 
description: static-ls ("static language server") reads static project
  information to provide IDE functionality through the language server
  protocol. static-ls will not generate this information on its own and instead
  will rely on the user to generate this information via separate programs
category: Development
maintainer: josephrsumabat@gmail.com
github: josephsumabat/static-ls
license: MIT
version: 0.1.2
build-type: Simple
extra-doc-files:
  - README.md
  - CHANGELOG.md
tested-with: 
  - GHC == 9.4.4
  - GHC == 9.6.3

dependencies:
  - array >= 0.5.4 && < 0.6
  - base >= 4.17.0 && < 4.19
  - containers >= 0.6.0 && < 0.7
  - unordered-containers >= 0.2 && < 0.3
  - directory >= 1.3.7 && < 1.4
  - errors >= 2.3.0 && < 2.4
  - extra >= 1.7.12 && < 1.8
  - filepath >= 1.4.1 && < 1.5
  - ghc >= 9.4.3 && < 9.7
  - ghc-paths >= 0.1.0 && < 0.2
  - ghcide >= 2.5.0 && < 2.8.0
  - haskell-lexer >=1.1.1 && <1.2.0
  - hiedb >= 0.6 && < 0.7
  - lsp >= 2.3 && < 2.6
  - lsp-types >= 2.1 && < 2.3
  - mtl >= 2.2.2 && < 2.4
  - parsec >= 3.1.0 && < 3.2
  - sqlite-simple >= 0.4.18 && < 0.5
  - template-haskell >= 2.19.0 && < 2.21
  - text >= 2.0.1 && < 2.1
  - bytestring >=0.10 && <0.13
  - transformers >= 0.5.6.2 && < 0.7
  - unliftio-core >= 0.2.1 && < 0.3
  - unliftio >= 0.2.1 && < 0.3
  - aeson >=2 && <2.3
  - text-rope >= 0.2 && < 0.3
  - co-log-core >= 0.3 && < 0.4
  - tree-sitter-simple
  - tree-sitter-haskell
  - tree-sitter-ast
  - haskell-ast
  - pretty-simple
language: GHC2021

default-extensions:
- ExplicitNamespaces
- FlexibleContexts
- OverloadedRecordDot
- OverloadedStrings
- NoFieldSelectors
- LambdaCase
- RecordWildCards
- TypeApplications

ghc-options:
  - -Wall
  - -Wno-name-shadowing 
  - -Wincomplete-record-updates

library:
  source-dirs: src
  ghc-options:
  - -fwrite-ide-info
  - -hiedir test/TestData/.hiefiles
  - -haddock

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - static-ls
  - optparse-applicative >= 0.17.0.0 && < 0.19
  generated-other-modules:
    - Paths_static_ls

tests:
  static-ls-test:
    dependencies:
    - static-ls
    defaults: hspec/hspec@main
    ghc-options:
      - -fwrite-ide-info
      - -fwrite-interface
      - -hiedir test/TestData/.hiefiles
      - -hidir test/TestData/.hifiles
      - -haddock

flags:
  dev:
    description: Defer type errors for development
    manual: true
    default: false

when:
  - condition: flag(dev)
    ghc-options:
    - -fwrite-ide-info
    - -hiedir .hiefiles
    - -hidir .hifiles
    - -fdefer-type-errors
    - -fno-defer-typed-holes
    - -Werror=deferred-type-errors
    - -Werror=deferred-out-of-scope-variables
