spec-version: 0.30.0
name: static-ls
author: Joseph Sumabat
synopsis: See README on Github for more information 
description: static-ls ("static language server") reads static project
  information to provide IDE functionality through the language server
  protocol. static-ls will not generate this information on its own and instead
  will rely on the user to generate this information via separate programs
category: Development
maintainer: josephrsumabat@gmail.com
github: josephsumabat/static-ls
license: MIT
version: 0.1.0
build-type: Simple

dependencies:
  - Cabal-syntax >= 3.10.1
  - Cabal-syntax < 3.11
  - array >= 0.5.5
  - array < 0.6
  - base >= 4.17.0
  - base < 4.19
  - containers >= 0.6.7
  - containers < 0.7
  - directory >= 1.3.8
  - directory < 1.4
  - errors >= 2.3.0
  - errors < 2.4
  - extra >= 1.7.13
  - extra < 1.8
  - filepath >= 1.4.100
  - filepath < 1.5
  - ghc >= 9.4.4
  - ghc < 9.7
  - ghc-paths >= 0.1.0
  - ghc-paths < 0.2
  - ghcide >= 1.10.0
  - ghcide < 1.11
  - hiedb >= 0.4.3
  - hiedb < 0.5
  - lsp >= 1.6.0
  - lsp < 1.7
  - lsp-types >= 1.6.0
  - lsp-types < 1.7
  - mtl >= 2.3.1
  - mtl < 2.4
  - sqlite-simple >= 0.4.18
  - sqlite-simple < 0.5
  - template-haskell >= 2.20.0
  - template-haskell < 2.21
  - text >= 2.0.2
  - text < 2.1
  - transformers >= 0.6.1
  - transformers < 0.7
  - unliftio-core >= 0.2.1
  - unliftio-core < 0.3

ghc-options:
  - -fwrite-ide-info
  - -fdefer-type-errors
  - -hiedir .hiefiles
  - -fdefer-type-errors
  - -Werror=deferred-type-errors
  - -Werror=deferred-out-of-scope-variables
  - -fno-defer-typed-holes
default-extensions:
- FlexibleContexts
- OverloadedRecordDot
- OverloadedStrings
- NoFieldSelectors
- LambdaCase

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - static-ls

tests:
  static-ls-test:
    dependencies:
    - static-ls
    defaults: hspec/hspec@main
