name: hlint
on:
  pull_request:
    branches: [main]
  push:
    branches:
      [ main ]

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v2
      with:
        version: '3.5'

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v2
      with:
        path:
          '[ "src/" , "app/" , "test/"]'
        fail-on: warning
